// <auto-generated />
using Coordina.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Coordina.Api.Infrastructure.Persistence.Migrations
{
  [DbContext(typeof(CoordinaDbContext))]
  [Migration("20260530123000_AddProjectBoards")]
  partial class AddProjectBoards
  {
  }
}
